#!/bin/bash

docker create \
	--name deluge \
	--net=host \
	--restart=always \
	-e PUID=0 -e PGID=0 \
	-e TZ=America/Sao_Paulo \
	-e UMASK_SET=022 \
	-v /storage/Download:/downloads \
	-v /storage/AppData/Deluge:/config \
	lsioarmhf/deluge

docker start deluge
