#!/bin/bash

docker create \
	--name=heimdall \
	--net=backend \
	-v /storage/AppData/Heimdall:/config \
	-e PGID=0 -e PUID=0  \
	-p 80:80 -p 443:443 \
	-e TZ=America/Sao_Paulo \
	lsioarmhf/heimdall

docker start heimdall
